<identifier>     = [a-zA-Z_][a-zA-Z0-9_]*
<literal-int>    = [0-9]+
<literal-float>  = [0-9]+ "." [0-9]+
<literal-char>   = "'" [^\'"'] "'"
<literal-string> = '"' [^'"'\\]* '"'
<literal-bool>   = "true" | "false"

<type-native>    = "i8" | "i16" | "i32" | "i64" | "ui8" | "ui16" | "ui32" | "ui64" | "f32" | "f64" | "str" | "bool" | "char"
<type-void>      = "void"

<program>        = <module-decl> <module-stmt>*
<module-decl>    = "module" <identifier> ( "::" <identifier> )* ";"
<module-stmt>    = (<const-decl> | <fun-decl>)*

<statement>      = <var-decl> | <assign-stmt> | <call-stmt> | <return-stmt>
<assign-stmt>    = <identifier> "=" <expression> ";"
<call-stmt>      = <fun-call> ";"

<var-decl>       = "var" <identifier> ":" <type-native> "=" <expression> ";"
<const-decl>     = [ "pub" ] "const" <identifier> ":" <type-native> "=" <expression> ";"

<fun-decl>       = [ "pub" ] "fun" <identifier> "(" [ <parameter-list> ] ")" "->" ( <type-native> | <type-void> ) ":" <statement>* "end"
<fun-call>       = <identifier> "(" [ <arg-list> ] ")"
<arg-list>       = <expression> ( "," <expression> )*

<parameter>      = <identifier> ":" <type-native>
<parameter-list> = <parameter> ( "," <parameter> )*

<return-stmt>    = "return" [ <expression> ] ";"

<expression>     = <term> ( ( "+" | "-" ) <term> )*

<term>           = <primary> ( ( "*" | "/" ) <primary> )*

<primary>        = <fun-call> 
                 | <identifier> 
                 | <literal-int> 
                 | <literal-float>
                 | <literal-string> 
                 | <literal-bool>
                 | <literal-char>
                 | "(" <expression> ")"